
public class prog79_exception2
{

	public static void main(String[] args)
	
	{
		try
		{
			
		}
		int a[]=new int[2];
		System.out.println("Access element three : " +a[3]);
	}
	catch(ArrayIndexOutOfBoundsException e)
	{
		System.out.println("Exception thrown : " +e);
		
	
	}
	System.out.scprintln("Out of the block");

	
	
		// TODO Auto-generated method stub

	}
}

